- hosts: all
  become: yes
  tasks:
    - name: Create Prometheus container
      docker_container:
        name: prometheus
        restart_policy: always
        image: prom/prometheus:latest  # Replace with the appropriate version
        volumes:
          - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          - /srv/prometheus/prometheus_alerts_rules.yml:/etc/prometheus/prometheus_alerts_rules.yml
          - prometheus_main_data:/prometheus
        command: >
          --config.file=/etc/prometheus/prometheus.yml
          --storage.tsdb.path=/prometheus
          --web.console.libraries=/etc/prometheus/console_libraries
          --web.console.templates=/etc/prometheus/consoles
          --web.enable-lifecycle
        published_ports:
          - "9090:9090"

    - name: Create Grafana container
      docker_container:
        name: grafana
        restart_policy: always
        image: grafana/grafana:latest  # Replace with the appropriate version
        volumes:
          - grafana-data:/var/lib/grafana
          - /srv/grafana/provisioning:/etc/grafana/provisioning
          - /srv/grafana/dashboards:/var/lib/grafana/dashboards
        published_ports:
          - "3000:3000"
